stages:
  - dependencies
  - test
  - build
  - deploy

dependencies_job:
  stage: dependencies
  script:
    - npm install
    - npm run build
    - cd frontend
    - npm install
    - npm run build
    - echo dependencies_passed!

# test_job:
#   stage: test
#   tags:
#     - node
#   script:
#     - npm install
#     - npm run test
#     - echo test_passed!

# build_job:
#   stage: build
#   tags:
#     - node
#   script:
#     - npm run build
#     - cd frontend 
#     - npm run build
#     - echo build_passed!

