stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  tags:
    - node
  script:
    - npm install
    - cd frontend
    - npm install
    - npm run build
    - echo build_passed!

# test_job:
#   stage: test
#   tags:
#     - node
#   script:
#     - npm install
#     - npm run test
#     - echo test_passed!

deploy:
  stage: deploy
  script:
  - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/pelican-express-development.git HEAD:master
  - echo "Deployed to production server"
  only:
  - development